# 环境配置
environment: test  # 当前运行环境：test/prod

# 环境参数
env:
  test:
    base_url: "http://api.test.com"
    username: "test_user"
    password: "test_pass"
    timeout: 10
    verify_ssl: false
  prod:
    base_url: "http://api.prod.com"
    username: "prod_user"
    password: "prod_pass"
    timeout: 30
    verify_ssl: true

# 通用请求头
headers:
  Content-Type: "application/json"
  User-Agent: "Mozilla/5.0"

# 添加邮件配置
email:
  smtp_host: "smtp.qq.com"
  smtp_port: 465  # QQ邮箱使用465端口进行SSL连接
  sender: "xxxxxx@qq.com" # 发送者邮箱
  password: "xxxxxxx"  # QQ邮箱授权码，修改为自己的授权码
  receivers: ["xxxxxx@163.com"] # 接收者邮箱
  subject: "API自动化测试报告" 